### ISSUE TITLE
这个工具会影响了其他的标签

### ISSUE THREAD

**Issue by angelen10** [MikeWang000000/ID3flac#1]
修改之后，确实 flac 的封面图是正常显示了，但是会导致该歌曲的所有信息都丢失了
<img width="591" alt="image" src="https://github.com/user-attachments/assets/c61a6a55-49a6-4156-8fa4-c54a893f42e6">
<img width="598" alt="image" src="https://github.com/user-attachments/assets/a9ebf55d-8451-4458-a8d8-1373ff4455e9">

**Comment by MikeWang000000** [comment]
这是一个demo，点开源代码可以看到，我这里确实只加了一个封面的 ID3 标签。

事实上原本的 Vobis 标签信息还是在的，只不过 Finder 读到了 ID3 标签就不去读 Vobis 标签了，导致信息显示不全，像是丢失了一样。

可以用 Kid3 等软件手动将 Vobis 标签复制到 ID3 标签区域补全，也可以将我没写完的 Python 代码补全后运行。

---

不过我不打算继续完善这个脚本了，因为这是手动创造了一个非标准的 FLAC 文件来应对 macOS 的 BUG。

这种非标准的 FLAC 文件，刚好对上 macOS 的 BUG，可以让 Finder 和 QuickTime Player 播放。

但是 FLAC 文件不应该出现 ID3 标签，这个工具强行加上的 ID3 标签会让其他平台的一些播放器识别成 MP3 导致无法播放；或者识别成其他格式放出刺耳的古怪声音。

**Comment by angelen10** [comment]
了解了，感谢感谢
